"""Key attributes mapping for each component subcategory.

Maps subcategory names to the essential attributes that engineers need
for component selection. Used to reduce token usage in search results.
"""

# Auto-generated from key-attributes-v3.md
# Regenerate with: python scripts/generate_key_attributes.py

KEY_ATTRIBUTES: dict[str, list[str]] = {
    "2G/3G/4G/5G Modules": ["Communication System", "Interface", "Voltage - Supply", "Current Consumption"],
    "3D Magnetic Sensors": [],
    "555 Timers / Counters": ["Voltage - Supply", "Frequency", "Current - Supply"],
    "AC Power Connectors": ["Voltage Rating", "Current Rating", "Standard", "Number of Ports"],
    "AC contactor": ["Coil voltage specifications", "Rated current", "Contact type", "Number of poles"],
    "AC-DC Controllers and Regulators": ["Topology", "Voltage - Supply", "Frequency - Switching", "Working Mode"],
    "AC-DC Power Modules": ["Output Voltage", "Voltage - Input(DC)", "Isolation Voltage(Vrms)", "Output Voltage Accuracy"],
    "ADCs/DACs - Special Purpose": ["Voltage Reference Value", "Number of Channels", "Voltage - Supply", "Voltage Reference Drift"],
    "ADI": ["Core Processor", "Speed", "Program Memory Size", "Number of I/O"],
    "ATMEL & AVR": ["Core Processor", "Speed", "Program Memory Size", "Number of I/O"],
    "Abolished Device": [],
    "Accelerometers": ["Acceleration Measurement Range (MAX)", "Interface", "Accelerometer Sensing Axis", "Voltage - Supply"],
    "Accessories": [],
    "Accessories - Inductors/Transformers": [],
    "Active Filters": [],
    "Adapter cable": [],
    "Adjustable Inductors": [],
    "Air Pump": [],
    "Aluminum Case/Porcelain Tube Resistance": ["Power(Watts)", "Resistance", "Tolerance"],
    "Aluminum Electrolytic Capacitors (Can - Screw Terminals)": ["Capacitance", "Voltage Rating", "Equivalent Series Resistance(ESR)", "Ripple Current"],
    "Aluminum Electrolytic Capacitors - Leaded": ["Capacitance", "Voltage Rating", "Equivalent Series Resistance(ESR)", "Ripple Current"],
    "Aluminum Electrolytic Capacitors - SMD": ["Capacitance", "Voltage Rating", "Equivalent Series Resistance(ESR)", "Ripple Current"],
    "Ambient Light Sensors": ["Interface", "Measurement Type", "Detection color", "Voltage - Supply"],
    "American fine thread wire screw sleeve": [],
    "Analog Front End (AFE)": ["Resolution(Bits)", "Sampling Rate", "Interface", "S/N Ratio"],
    "Analog Switches - Special Purpose": ["Number of Channels", "Voltage - Supply", "Switch Circuit", "-3dB Bandwidth"],
    "Analog Switches, Multiplexers": ["Number of Channels", "Voltage - Supply", "Ron", "Bandwidth"],
    "Analog to Digital Converters (ADC)": ["Resolution(Bits)", "Sampling Rate", "number of channels", "Interface"],
    "Angular contact ball bearing": [],
    "Antenna spring": ["frequency range", "impedance", "size"],
    "Antennas": ["Frequency(Center/Band)", "Antenna Type", "Peak Gain", "VSWR"],
    "Application Specific Clock/Timing": ["Voltage - Supply", "Current - Supply"],
    "Audio Amplifiers": ["Output Power", "Class", "Voltage - Supply"],
    "Audio Connectors": ["Connector Type", "Voltage Rating", "Current Rating"],
    "Audio Interface ICs": ["Sampling Rate", "Voltage - Supply", "Type", "Interface"],
    "Audio Transformers": [],
    "Audio cable": ["Line length", "Wire diameter", "Core material", "Joint type"],
    "Automobile Connectors": ["Current Rating", "Voltage Rating", "Number of PINs", "Type"],
    "Automotive Fuses": ["Current Rating", "Voltage Rating (DC)", "Type"],
    "Automotive Relays": ["Coil Voltage", "Contact Form", "Contact Rating", "Switching Voltage(Max)"],
    "Avalanche Diodes": ["Voltage - DC Reverse(Vr)", "Avalanche Energy", "Current - Rectified", "Voltage - Forward(Vf@If)"],
    "Aviation connector/waterproof connector": [],
    "BV Terminal": ["Wire Gauge - AWG", "Wire Gauge - mm2", "Connector Type"],
    "Balun": ["Frequency Range", "Impedance - Unbalanced/Balanced", "Insertion Loss (Max)", "Return Loss(Min)"],
    "Banana Connectors / Alligator Clips": ["Voltage Rating", "Current Rating", "Connector Type", "Color"],
    "Barrier Terminal Blocks": ["Voltage Rating (Max)", "Current Rating", "Pitch", "Number of Positions or Pins"],
    "Battery Management": ["Type of Battery", "Number of Cells", "Charge Current - Max", "Voltage - Supply"],
    "Battery accessories": ["Applicable battery specifications", "Connector type"],
    "Battery connector": ["Type", "Applicable battery specifications"],
    "Bipolar (BJT)": ["Collector - Emitter Voltage VCEO", "Current - Collector(Ic)", "DC Current Gain", "type"],
    "Blade / Shrapnel Contact Battery Connectors": ["Pitch", "Number of Pins", "Contact Material"],
    "Block": [],
    "Bluetooth Modules": ["Interface Type", "Output Power (Max)", "Utilized IC / Part"],
    "Board end": ["Specifications", "type"],
    "Board-to-Board and Backplane Connector": [],
    "Body Worn Camera": [],
    "Bolt": [],
    "Bridge Rectifiers": ["Voltage - DC Reverse(Vr)", "Current - Rectified", "Voltage - Forward(Vf@If)", "Type"],
    "Brushed DC Motor Drivers": ["Output Current", "Voltage - Supply", "Peak Current", "Operating Temperature"],
    "Brushless DC (BLDC) Motor Driver": ["Drive Type", "Output Current", "Voltage - Supply", "Operating Temperature"],
    "Buffers, Drivers, Receivers, Transceivers": ["Voltage - Supply", "output type", "Propagation Delay", "Number of Bits per Element"],
    "Button And Strip Battery Connector": [],
    "Button head": [],
    "Button indicator light accessories": [],
    "Button switch accessories": [],
    "Button/Signal Lamp/Main Switch": [],
    "Buzzer Plates": [],
    "Buzzer/Electronic Beeper": [],
    "Buzzers": ["Voltage - Supply", "Sound Pressure Level", "Frequency", "Driver Circuitry"],
    "CAN Bus Modules": ["Data Rate", "Voltage - Supply", "Type", "Isolation"],
    "CAN Controllers": ["Data Rate", "Voltage - Supply", "Type", "Current - Supply"],
    "CAN Transceivers": ["Data Rate", "Voltage - Supply", "Type", "Current - Supply", "Quiescent Supply Current"],
    "CPLD/FPGA": ["Number of Logic Elements/Blocks", "Number of Macrocells", "Number of I/O", "Programmable Type"],
    "CYPRESS": ["Core Processor", "Speed", "Program Memory Size", "Number of I/O"],
    "Cable Supports and Fasteners": [],
    "Cable Terminals and Intermediate Joints": [],
    "Cable Ties and Zip Ties": [],
    "Cable Trays, Ducts": [],
    "Cable passer": [],
    "Cables and wire clips": ["size", "frequency range", "impedance", "working temperature"],
    "Capacitive Sensor IC": ["Interface", "Number of Channels", "Sensor Capacitance Range", "Supply - Voltage"],
    "Capacitor Networks, Arrays": ["Capacitance", "Voltage Rating", "Number of Capacitors", "Circuit Type"],
    "Carriage bolt": ["standard", "Specifications"],
    "Center": [],
    "Ceramic Filters": ["Frequency - Center", "Insertion Loss", "Impedance", "Bandwidth"],
    "Ceramic Resonators": ["Frequency", "Resonant Impedance", "Built-in Load Capacitance"],
    "Ceramic antenna": [],
    "Ceramic plugin capacitor": [],
    "Charge Pumps": ["Output Voltage", "Output Current", "Operating Voltage", "Switching Frequency"],
    "Charging Port Test Board": [],
    "Chip Resistor - Surface Mount": ["Resistance", "Tolerance", "Power(Watts)"],
    "Chuck": [],
    "Circular Connectors & Cable Connectors": ["Voltage Rating", "Current Rating", "Number of Pins", "Gender"],
    "Circular DIN Connectors": ["Voltage Rating", "Current Rating", "Number of Pins", "Gender"],
    "Clamp Filters (Ferrite Core with Case)": ["Impedance @ Frequency", "Applicable Cable Type", "Inner Diameter"],
    "Clamping Plate": [],
    "Clock Buffers, Drivers, Distributors": ["Voltage - Supply", "Output Frequency(Max)", "Number of outputs", "Number of Inputs"],
    "Clock Generators, PLLs, Frequency Synthesizers": ["Voltage - Supply", "Output Frequency(Max)", "Interface", "Number of Outputs"],
    "Clock Multipliers": [],
    "Clock and Data Recovery / Retiming": ["Voltage - Supply"],
    "Closed-End Terminal": ["Wire Gauge - AWG", "Wire Gauge - mm2", "Connector Type"],
    "Coaxial Connectors (RF)": ["Connector Type", "Impedance", "Frequency", "RF Series"],
    "Coaxial cable (RF)": [],
    "Cold press terminals/Terminal blocks": [],
    "Cold shrink tape / tubing": [],
    "Cold-pressed Terminals": ["Wire Gauge - mm2", "Wire Gauge - AWG", "Connector Type"],
    "Color Ring Inductors / Through Hole Inductors": ["Inductance", "Current Rating", "DC Resistance(DCR)", "Tolerance"],
    "Common Mode Filters": ["Voltage Rating - DC", "Impedance @ Frequency", "Current Rating", "Number of Lines"],
    "Communication accessories": [],
    "Comparators": ["Number of Channels", "Maximum Power Supply Range (Vdd-Vss)", "Output Type", "Response Time (tr)"],
    "Composite gasket": [],
    "Comprehensive Electronic": [],
    "Compression Spring": [],
    "Conical pin": [],
    "Connecting accessories": [],
    "Connector Accessories": [],
    "Connector Housings": [],
    "Consumables for Own Use": [],
    "Contactor accessories": [],
    "Cooling fan": [],
    "Counters, Dividers": ["Number of Bits per Element", "Voltage - Supply", "Count Rate", "Logic Type"],
    "Crimp contact pins": [],
    "Cross Slotted Head Screws": [],
    "Cross pan head machine screw three combinations": [],
    "Cross pan head machine screws": ["Thread diameter", "size", "length"],
    "Cross pan head triangular thread machine screw": [],
    "Cross slot countersunk flat tail self-tapping screws": [],
    "Cross slot countersunk machine screw": [],
    "Cross slot countersunk screw with drill tail self-tapping screw": [],
    "Cross slot large flat head machine screw": ["diameter", "length", "pitch"],
    "Cross slot large flat head self-tapping screw": [],
    "Cross slot pan head machine screw": [],
    "Cross slot pan head screws and flat washer combination": [],
    "Cross slot pan head screws and spring washer combination": ["standard", "Specifications"],
    "Cross slot pan head self-tapping screw": [],
    "Cross slot pan head self-tapping screws with insulation": ["standard", "Specifications"],
    "Cross slot round head flat tail self-tapping screws": ["Head diameter", "material", "specifications"],
    "Cross slot washer head self-drilling self-tapping screw": [],
    "Crystal Filters": ["Frequency - Center", "Insertion Loss", "Pass Bandwidth", "Impedance"],
    "Crystal Oscillators": ["Frequency", "Voltage - Supply", "Output Type", "Frequency Stability"],
    "Crystals": ["Frequency", "Load Capacitance", "Frequency Stability", "Type"],
    "Current Sense Amplifiers": ["Differential Voltage", "Bandwidth", "Gain Bandwidth Product"],
    "Current Sense Resistors / Shunt Resistors": ["Resistance", "Tolerance", "Temperature Coefficient", "Power(Watts)"],
    "Current Sense Transformers": ["Turns Ratio", "Rated input Current", "Isolation Voltage(Vrms)", "DCR Primary Side (Max)"],
    "Current Sensors": ["Voltage - Supply", "Current Range", "Sensitivity", "Response Time"],
    "Current Source / Constant Current Source": ["Output Current", "Voltage - Supply", "Tolerance", "Type"],
    "Cylindrical battery": [],
    "Cylindrical roller bearings": [],
    "D-Sub / VGA Connectors": ["Number of Pins", "Gender", "Connector Type", "Mounting Type"],
    "D-Sub Cable": [],
    "DAQ": [],
    "DC Power Connectors": ["Current Rating", "Voltage Rating (Max)", "Connector Type", "Inside Contact Diameter"],
    "DC contactor": [],
    "DC-AC Module (Inverter)": [],
    "DC-DC Controllers": ["Input Voltage", "Topology", "Switching Frequency", "Synchronous Rectification"],
    "DC-DC Converters": ["Voltage - Supply", "Output Voltage", "Output Current", "Frequency - Switching", "Topology"],
    "DC-DC Power Modules": ["Output Voltage", "Voltage - Supply", "Output Current(Max)", "Switching Frequency", "Function"],
    "DDR SDRAM": ["Memory Size", "Clock Frequency", "Voltage - Supply", "Memory Format"],
    "DI/DO Isolators": [],
    "DIN41612 Connectors": ["Current Rating", "Pitch", "Number of Pins", "Number of Rows"],
    "DIP Switches": ["Number of Positions", "Voltage Rating", "Current Rating", "Type"],
    "DRAM": ["Memory Size", "Clock Frequency", "Voltage - Supply", "Memory Format"],
    "DVI Connectors": ["Rated Voltage", "Current Rating", "Connector Type", "Gender"],
    "Daily Necessities": [],
    "Darlington Transistor Arrays": ["number of channels", "Current - Collector(Ic)", "Input Current(on)", "Output Leakage Current(Icex)"],
    "Darlington Transistors": ["Collector - Emitter Voltage VCEO", "Current - Collector(Ic)", "DC Current Gain", "Type"],
    "Dedicated cable assemblies": [],
    "Deep groove ball bearing": [],
    "Development Boards & Kits": ["CPU", "Number of I/O", "ROM Size", "Power Supply Type"],
    "Differential Amplifiers": ["Gain Bandwidth Product", "CMRR", "Slew Rate", "Max Power Supply Range"],
    "Differential Pressure Sensor": [],
    "Digital Comparators": ["Number of Channels", "Propagation Delay", "Voltage - Supply", "Output"],
    "Digital Isolators": ["Number of Forward Channels", "Number of Reverse Channels", "Data Rate(Max)", "Isolation Voltage(Vrms)"],
    "Digital Isolators (with Power)": ["Number of Forward Channels", "Number of Reverse Channels", "Data Rate(Max)", "Isolation Voltage(Vrms)"],
    "Digital Potentiometers": ["Resistance Value (Ohms)", "Number of Channels", "Tolerance", "Interface"],
    "Digital Signal Processors (DSP/DSC)": ["Maximum Speed", "Voltage - Supply", "FLASH Size", "Number of I/O"],
    "Digital Transistors": ["Collector - Emitter Voltage VCEO", "Input Resistor", "Resistor Ratio", "type"],
    "Digital Tube Drivers": ["Voltage - Supply", "Operating Temperature"],
    "Digital to Analog Converters (DAC)": ["Resolution(Bits)", "Number of Channels", "Output Type", "Interface"],
    "Digitally Controlled Oscillators (DCOs)": [],
    "Diodes - General Purpose": ["Voltage - DC Reverse(Vr)", "Current - Rectified", "Diode Configuration", "Voltage - Forward(Vf@If)"],
    "Diodes - Rectifiers - Fast Recovery": ["Voltage - DC Reverse(Vr)", "Current - Average Rectified", "Reverse Recovery Time (trr)", "Voltage - Forward(Vf@If)"],
    "Diodes - Variable Capacitance": ["DC Reverse Voltage(Vr)", "Diode Capacitance", "Capacitance Ratio", "Diode Configuration"],
    "Direct Digital Synthesis (DDS)": ["The main FCLK", "Resolution (Bits)", "Voltage - Supply"],
    "DisplayPort (DP) Connector": ["Current Rating", "Connector Type", "Number of Ports"],
    "Disposable fuses": ["Current Rating", "Voltage Rating (AC)", "Type"],
    "Drawbar / Pull stud": [],
    "Drive Clamp": [],
    "Duplexers": ["Operating Temperature"],
    "Dupont wire / terminal block wire / electronic wire": ["Wire gauge", "RatedCurrent", "Maximum voltage", "NumberOfWires(PCS)"],
    "E Terminal": ["Wire Gauge - AWG", "Wire Gauge - mm2", "Connector Type"],
    "E-ink Display": [],
    "EEPROM": ["Memory Size", "Interface", "Voltage - Supply", "Clock Frequency"],
    "EMC Filters": [],
    "EMI/RFI Filters (LC, RC Networks)": ["Resistance", "Capacitance", "ESD Protection"],
    "EN Terminal": [],
    "ESD Protection Devices": [],
    "ESD and Surge Protection (TVS/ESD)": ["Reverse Stand-Off Voltage (Vrwm)", "Clamping Voltage", "Peak Pulse Power", "Voltage - Breakdown"],
    "Edgeboard Connectors": [],
    "Electric Energy Meter": ["Voltage Range", "Current Range", "Accuracy", "Power Type"],
    "Electrical measurement module": [],
    "Electromechanical Contactor": [],
    "Encoder": [],
    "Energy Metering": ["Number of Channels", "Dynamic Range", "Interface", "Voltage - Supply"],
    "Ethernet Connectors / Modular Connectors (RJ45 RJ11)": ["Number of Ports", "Connector Type", "PoE", "Shielding"],
    "Ethernet Controllers": ["Ethernet Speed Standards", "MAC Interface", "Integrated PHY", "Voltage - Supply"],
    "Ethernet Modules": [],
    "Ethernet Switches": ["Ethernet Speed Standards", "Number of Channels", "VLAN Support", "Data Rate"],
    "Ethernet Transceivers": ["Ethernet Speed Standards", "MAC Interface", "Data Rate", "Voltage - Supply"],
    "External hexagon bolts and nut kit": [],
    "External hexagon self-tapping screws": ["standard", "Specifications"],
    "FET Input Amplifiers": ["Ib - Input Bias Current", "Gain Bandwidth Product", "Slew Rate"],
    "FFC Cable (Flexible Flat Cable)": ["Number of Pins", "Pitch", "Total Length", "Contact Location"],
    "FFC, FPC Connector Assemblies": ["Pitch", "Number of Contacts", "Locking Feature", "Contact Type"],
    "FIFOs Memory": ["Voltage - Supply", "Clock Frequency", "Memory Size", "Data Bus Width"],
    "FRAM": ["Memory Size", "Interface", "Voltage - Supply", "Program / Erase Cycles"],
    "FRD / MPD Terminal": ["Wire Gauge - AWG", "Wire Gauge - mm2", "Connector Type"],
    "Fast Recovery / High Efficiency Diodes": ["Reverse Recovery Time (trr)", "Voltage - DC Reverse(Vr)", "Current - Rectified", "Voltage - Forward(Vf@If)"],
    "Feed Through Capacitors": ["Nominal Capacitance", "Voltage Rating", "Current Rating", "DC Resistance"],
    "Feed-Voltage/Radio-Frequency Insulator": [],
    "Female Headers": ["Pitch", "Number of Positions", "Number of Rows", "Current Rating"],
    "Female-Female Hex Standoff": [],
    "Female-Female Round Standoff": [],
    "Ferrite Beads": ["Impedance @ Frequency", "Current Rating", "DC Resistance(DCR)", "Number of Circuits"],
    "Ferrite magnetic beads": [],
    "Fiber Optic / Laser Sensors": [],
    "Fiber Optic Connectors": [],
    "Fiber optic sensor": [],
    "Film Capacitors": ["Capacitance", "Voltage Rating", "Tolerance"],
    "Filter capacitors": [],
    "Fixed Attenuator": [],
    "Flat Flexible Jumpers, Cables (FFC, FPC)": [],
    "Flip Flops": ["Voltage - Supply", "Clock Frequency", "Number of Bits per Element", "Trigger Type"],
    "Float Level Senors": ["Voltage - Supply", "Number of Channels", "Contact Type", "Interface Type"],
    "Flow Sensors": [],
    "Font chips": ["Character Set", "Word Size", "Clock Frequency", "Interface"],
    "Force Sensors, Load Cells": ["Operating Force", "Voltage - Supply", "Life"],
    "Fs FlatMagneticRing": [],
    "Fuse/Current Protector": ["Current Rating", "Rated Voltage (DC)", "Features"],
    "Fuseholders": ["Fuse Type", "Fuse Diameter", "Fuse Length"],
    "GNSS Modules": ["GNSS Type", "Voltage - Supply", "Accuracy", "Sensitivity"],
    "GaN Transistors (GaN HEMT)": ["Voltage - Supply", "Features", "Fall Time"],
    "Gas Discharge Tube Arresters (GDT)": ["Impulse Breakdown Voltage", "Voltage - DC Spark Over", "Impulse Discharge Current", "Number of Poles"],
    "Gas Flow Sensors": [],
    "Gas Sensors": ["Interface", "Voltage - Supply", "Current - Supply", "Operating Temperature"],
    "Gate Drive Optocoupler": ["Isolation Voltage(Vrms)", "Output Current(Max)", "CMTI(kV/us)", "Voltage - Supply (Driver)"],
    "Gate Drivers": ["Number of Drivers", "Driven Configuration", "Voltage - Supply", "Current - Output High(IOH)"],
    "Generator": [],
    "Glass Discharge Tubes": ["Voltage - DC Spark Over", "Surge Current Capacity", "Capacitance"],
    "Global Sourcing Parts": [],
    "HDMI Connectors": ["Connector Type", "Gender", "Voltage Rating", "Current Rating"],
    "HDSC": [],
    "HWDG": [],
    "Hall Switches": ["Voltage - Supply", "Type", "Operation Points", "Release Points"],
    "Hand Protection": [],
    "Hard Disk Connector (SAS/SATA/M.2)": ["Connector Type", "Number of Pins", "Interface Form"],
    "Heart Rate Sensors": ["Interface", "Voltage - Supply", "Number of LED Drivers", "Resolution(Bits)"],
    "Heat shrink tubing": [],
    "Heat sink / cooling fin": ["Shape", "ProductSize", "TextureOfMaterial"],
    "Hex Washer Head Self-Drilling Screw": [],
    "Hex socket screws with countersunk head": [],
    "Hexagon socket cylindrical head screw": ["Nominal diameter", "length", "pitch"],
    "Hexagon socket flange screw with serrated flange": [],
    "Hexagonal nuts": [],
    "Hexagonal nylon locking nuts": [],
    "High Effic Rectifier": ["Reverse Voltage", "Average Rectified Current", "Forward Voltage", "Reverse Recovery Time"],
    "High Frequency / RF Relay": [],
    "Hook Terminal": ["Connector Type"],
    "Horn-Type Electrolytic Capacitors": ["Capacitance", "Voltage Rating", "Equivalent Series Resistance(ESR)", "Ripple Current"],
    "Hose clamp": [],
    "Hot-dip galvanized screw": [],
    "Housing Contact": ["Contact Material", "Contact Plating", "Wire Gauge - mm2", "Wire Gauge - AWG"],
    "Housings (Wire To Board / Wire To Wire)": ["Pitch", "Number of PINs Per Row", "Number of Rows", "Reference Series"],
    "Hub/Adapter": [],
    "Human Body Sensing Sensor": ["Voltage - Supply", "Number of Sensitive Elements", "Operating Wavelength", "Window Size"],
    "Hybrid Aluminum Electrolytic Capacitors": ["Capacitance", "Voltage Rating", "Equivalent Series Resistance(ESR)", "Ripple Current"],
    "I/O Expanders": ["Number of I/O", "Clock Frequency", "Interface", "Voltage - Supply"],
    "I2C Isolators": ["Isolation Voltage(Vrms)", "CMTI(kV/us)", "Clock Direction", "Operating Temperature"],
    "IC / Transistor Socket": ["Pitch", "Number of Positions", "Adaptation Package Type", "Contact Material"],
    "IDC Connectors": ["Number of Positions or Pins", "Pitch", "Current Rating", "Connector Type"],
    "IEEE 1394 / Firewire Connector": ["Voltage Rating", "Current Rating", "Number of Pins", "Connector Type"],
    "IGBT Transistors / Modules": ["Collector-Emitter Breakdown Voltage (Vces)", "Current - Collector(Ic)", "Vce Saturation(VCE(sat))", "Gate Charge(Qg)"],
    "Image Sensors": ["Sensor Type", "Optical Format(inch)", "Pixel Size", "Active Pixel Array"],
    "Indicator Light": [],
    "Inductor core": [],
    "Inductors (SMD)": ["Inductance", "Current - Saturation (Isat)", "DC Resistance(DCR)", "Current Rating"],
    "Industrial Belts": [],
    "Industrial Computer": [],
    "Industrial terminal blocks": [],
    "Infrared (IR) LEDs": ["Peak Wavelength", "Radiant Flux", "Viewing Angle", "Voltage - Forward(Vf)"],
    "Instrumentation Amplifiers": ["CMRR", "Gain Bandwidth Product", "Vos - Input Offset Voltage", "Slew Rate"],
    "Intelligent Power Modules (IPM)": [],
    "Interface - PCIs / PCIEs": ["Voltage - Supply", "Versions", "Data Rate", "Number of Channels"],
    "Interface - Specialized": ["Voltage - Supply", "Operating Temperature"],
    "Internal hexagon cylindrical head flat washer three combinations": ["standard", "pitch", "Specifications"],
    "Internal hexagonal flat round head screw with washer": [],
    "Inverter": [],
    "Inverters": ["Voltage - Supply", "Propagation Delay", "Number of Circuits", "Series"],
    "Isolated ADCs": ["Isolation Voltage(Vrms)", "CMTI(kV/us)", "Propagation Delay(tpd)", "Voltage - Supply(VCCA)"],
    "Isolated ADCs with power": [],
    "Isolated CAN Transceivers": ["Isolation Voltage(Vrms)", "Data Rate(Max)", "Number of Channels", "CMTI(kV/us)"],
    "Isolated CAN Transceivers (with Power)": ["Isolation Voltage(Vrms)", "Data Rate(Max)", "Number of Channels", "CMTI(kV/us)"],
    "Isolated Comparators": [],
    "Isolated DC/DC Converters": ["Isolation voltage", "Vout", "Output Power", "Ripple"],
    "Isolated I2C (with Power)": ["Isolation Voltage(Vrms)", "Voltage - Supply", "CMTI(kV/us)", "Output Voltage"],
    "Isolated LVDS Buffers": ["Number of Forward Channels Groups", "Number of Reverse Channels Groups", "Isolation Voltage(Vrms)", "CMTI(kV/us)"],
    "Isolated Power Modules": ["Voltage - Supply", "Output Voltage", "Output Power", "Isolation Voltage(Vrms)"],
    "Isolated RS-232 Transceivers": [],
    "Isolated RS-232 Transceivers (with Power)": ["Data Rate(Max)", "Isolation Voltage(Vrms)", "Number of Drivers", "Number of Receivers"],
    "Isolated RS-485/422 Transceivers": [],
    "Isolated RS-485/422 Transceivers with power": ["Isolation Voltage(Vrms)", "Communication Mode", "Voltage - Supply", "Output Voltage"],
    "Isolated USB ICs": [],
    "Isolated USB ICs with power": ["Isolation Voltage(Vrms)", "Protocol", "Voltage - Supply", "Output Voltage"],
    "Isolation Amplifiers": ["Isolation Voltage(Vrms)", "-3dB Bandwidth", "Gain", "CMTI(kV/us)"],
    "Isolation Amplifiers with power": [],
    "Isolation-Solid State Relays": [],
    "Isolators - Gate Drivers": ["Voltage - Supply (Input)", "Number of Channels", "Load Type", "Operating Temperature"],
    "JFETs": ["Gate-Source Cutoff Voltage (VGS(off))", "Drain Current (Idss)", "RDS(on)", "FET Type"],
    "Jitter Attenuators": [],
    "Joint": [],
    "Jumper wire/enamelled wire/pre-cable": ["RatedCurrent", "Rated VoltageVDC", "CoreWireGauge", "Sheath (insulation) material"],
    "Keylock Switches": ["Voltage Rating", "Contact Current", "Self Lock / No Lock", "Circuit"],
    "Knife Terminal": ["Contact Plating", "Contact Material", "Wire Gauge - AWG"],
    "LCD Drivers": ["Display Configurations (bit)", "Voltage - Supply", "Duty cycle", "Interface"],
    "LCD Screen": ["Dot Pixels", "Size", "Interface", "Voltage - Supply"],
    "LCDH": [],
    "LED - High Brightness": ["Color Temperature", "Luminous Flux", "Power(Watts)", "CRI (Color Rendering Index)"],
    "LED Displays - 7-Segment": ["Digit/Alpha Size", "Color", "Common Cathode/Anode", "Voltage - Forward(Vf)"],
    "LED Dot Matrix": ["Configuration (Rows x Columns)", "Color", "Viewing Angle", "Voltage - Forward(Vf)"],
    "LED Dot Matrix and Cluster": ["Illumination Color", "Number of Digits", "Luminous Intensity", "Wavelength - Dominant"],
    "LED Drivers": ["Output Current", "Type", "Number of Channels", "Voltage - Input (DC)"],
    "LED Indication - Discrete": ["Illumination Color", "Luminous Intensity", "Viewing Angle", "Voltage - Forward(Vf)"],
    "LED Protection": ["Trigger Voltage", "Hold Current", "On - State Voltage(VT)", "Current - Leakage"],
    "LED Segment Displays": ["Illumination Color", "Number of Characters", "Light Intensity", "Display Type"],
    "LED Tube": [],
    "LED isolation column": ["Type"],
    "LED light strip": [],
    "LIN Transceivers": ["Voltage - Supply", "Number of Drivers", "Number of Receivers", "ESD Protect"],
    "LVDS ICs": ["Voltage - Supply", "Data Rate", "Type", "Number of Drivers"],
    "Labels, tags": [],
    "Lack of specifications": [],
    "Laser Diodes": ["Operating Wavelength", "Peak Power", "Operating Current", "Operating Voltage"],
    "Laser Drivers": ["Bias Current", "Voltage - Supply", "Data Rate", "Operating Temperature"],
    "Laser Modules": ["Wavelength", "Peak Power", "Operating Voltage", "Operating Temperature"],
    "Latches": ["Voltage - Supply", "Propagation Delay", "Number of Channels", "Output Type"],
    "Leakage Protection ICs": ["Tripping Voltage", "Voltage - Supply", "Current - Supply"],
    "Light Bars, Arrays": ["Color", "Number of Segments", "Mounting Style", "Voltage - Forward(Vf)"],
    "Light Pipes": ["Color", "Height", "Mounting Style"],
    "Lighting Drivers & Controllers": ["Driver Type", "Switch Frequency", "Operating temperature"],
    "Lighting transformers": [],
    "Limit Switch/Travel Switch": [],
    "Limit Switches": ["Voltage Rating (DC)", "Current Rating (DC)", "Current Rating (AC)", "Termination Style"],
    "Linear - Analog Multipliers, Dividers": ["Quadrant", "Bandwidth", "Slew Rate"],
    "Linear Hall Sensors": ["Voltage - Supply"],
    "LoRa Modules": ["Modulation System", "Voltage - Supply", "Output Power", "Sensitivity"],
    "Logic Gates": ["Number of Channels", "Voltage - Supply", "Propagation Delay", "Logic Type"],
    "Logic Output Optoisolators": ["Number of Channels", "Isolation Voltage(Vrms)", "Data Rate", "Forward Current(If)"],
    "Low Noise Amplifiers (LNA) - RF": ["Frequency Range", "Noise Figure", "Gain", "P1dB"],
    "MEGAWIN": ["Core Processor", "Speed", "Program Memory Size", "Number of I/O"],
    "MEMS Microphones": ["Voltage - Supply", "Output Type", "Sensitivity", "S/N Ratio"],
    "MICROCHIP": ["Core Processor", "Speed", "Program Memory Size", "Number of I/O"],
    "MOSFETs": ["Drain to Source Voltage", "Gate Threshold Voltage (Vgs(th))", "Current - Continuous Drain(Id)", "RDS(on)"],
    "MRO presale new products": [],
    "Magnetic Angle Sensors": [],
    "Magnetic Block": [],
    "Magnetic Chip Collector": [],
    "Magnetic Chuck": [],
    "Magnetic Latching Relays": ["Coil Voltage", "Contact Form", "Switching Current(Max)", "Switching Voltage(Max)"],
    "Magnetic Pickup Tool": [],
    "Magnetic Tapping Attachment": [],
    "Magnetic Wire Terminal": [],
    "Male-Female Round Standoff": [],
    "Mechanical Keyboard Shaft": ["Conduction Travel", "Operation Force", "Life", "Axis Type"],
    "Mechanical parts": [],
    "Memory - Configuration Proms for FPGAs": [],
    "Memory - Serial MCP (Multi Chip Package)": ["Memory Size of Flash", "Type of memory", "Clock Frequency", "Voltage - Supply"],
    "Memory Connector (DDR)": [],
    "Memory Controllers": ["Controller Type", "Function", "Voltage - Supply", "Supply current"],
    "Metal Dome Pot": ["Travel", "Operating Force", "Switching Life", "Height"],
    "Metal Products * SMT Copper Sheet": ["Thickness", "MaterialQuality", "Specifications"],
    "Metal gasket": [],
    "Mica and PTFE Capacitors": ["Capacitance", "Voltage Rating", "Tolerance"],
    "Micro switch": [],
    "Micro-Match Connector": [],
    "Microcontrollers (MCU/MPU/SOC)": ["CPU Core", "CPU Maximum Speed", "Program Storage Size", "RAM Size", "Number of I/O"],
    "Microphones": ["Voltage - Supply", "Sensitivity", "S/N Ratio", "Direction"],
    "Microscope Accessories": [],
    "Milling Chuck": [],
    "Miniature Circuit Breaker": [],
    "Miniature leakage protection circuit breaker": [],
    "Modular - Flat Cables": [],
    "Modules": [],
    "Monostable Multivibrators": ["Voltage - Supply", "Function", "Propagation Delay", "Number Of Channels"],
    "Motor Driver Boards, Modules": [],
    "Motor Driver ICs": [],
    "Multi-Directional Switches": [],
    "Multidirectional Switch": ["Voltage Rating", "Contact Current", "Mounting Type"],
    "Multilayer Ceramic Capacitors MLCC - Leaded": ["Capacitance", "Voltage Rating", "Tolerance", "Temperature Coefficient"],
    "Multilayer Ceramic Capacitors MLCC - SMD/SMT": ["Capacitance", "Voltage Rating", "Tolerance", "Temperature Coefficient"],
    "NAND FLASH": ["Memory Size", "Interface", "Voltage - Supply", "Data Retention"],
    "NOR FLASH": ["Memory Size", "Interface", "Voltage - Supply", "Clock Frequency"],
    "NTC Thermistors": ["Resistance @ 25℃", "Resistance Tolerance", "B Constant (25℃/100℃)", "Power(Watts)"],
    "NUVOTON": ["Core Processor", "Speed", "Program Memory Size", "Number of I/O"],
    "NXP MCU": ["Core Processor", "Speed", "Program Memory Size", "Number of I/O"],
    "Navigation Switches, Joystick": ["Voltage Rating", "Total Resistance", "Mounting Type", "Toggle reset"],
    "Network Clock Synchronization (SyncE, IEEE 1588)": [],
    "Network cable/modular cable": ["Category", "Type", "TransmissionSpeed", "Length"],
    "New Arrivals": [],
    "Niobium Oxide Capacitors": ["Capacitance", "Voltage Rating", "Equivalent Series Resistance(ESR)", "Tolerance"],
    "No specification for star making plan": [],
    "No-Break Wire Clamp": [],
    "Noise Suppressors": ["Magnetic Conductivity-u'", "Length", "Width"],
    "Non-Volatile Memory (ROM)": ["Memory Size", "Voltage - Supply", "Data Retention", "Interface"],
    "Nut": ["Nominal diameter", "pitch", "Thread type"],
    "OLED Display": ["Dot Pixels", "Size", "Interface", "Type of Drive"],
    "OLED Drivers": [],
    "ORing Controllers": ["Input Voltage (Vin)", "Peak Output Current(Sink)", "Gate Drive Voltage", "FET Type"],
    "Ohmmeter": [],
    "Open type flat round head blind rivet": ["Rivet diameter", "Nominal length", "material"],
    "Operational Amplifier": ["Gain Bandwidth Product", "Number of Channels", "Slew Rate", "Maximum Power Supply Range (Vdd-Vss)"],
    "Optical Module Connector": [],
    "Optocoupler Emulator (Optocoupler Replacement)": [],
    "Optoelectronics Accessories": ["Type"],
    "Other Processors and Microcontrollers (MCUs)": ["Core Processor", "Speed", "Program Memory Size", "Number of I/O"],
    "Other Seals": [],
    "Other antennas": [],
    "Other contactors": [],
    "Other electrical auxiliary materials": [],
    "Other hardware": ["size", "diameter", "length"],
    "Other industrial control products": [],
    "Other modules/collectors": [],
    "Other nuts": ["diameter", "pitch", "material"],
    "Other rivets": [],
    "Other screws": [],
    "Other sensors": [],
    "Oven Controlled Crystal Oscillators (OCXOs)": ["Frequency", "Output Type", "Voltage - Supply", "Frequency Stability"],
    "PC Board Spacer": [],
    "PCB Welding Terminal": [],
    "PCI / PCIe Connector": ["Versions", "Number of Pins", "Connector Type", "Number of Data Pins"],
    "PFC Controllers": ["Voltage - Supply", "Frequency - Switching", "Operating Temperature"],
    "PIN Diodes": ["Voltage - DC Reverse(Vr)", "Diode Configuration", "Operating Junction Temperature Range"],
    "PM2.5 Sensors": [],
    "PSRAM": ["Voltage - Supply", "Access Time"],
    "PTC Thermistors": ["Resistance @ 25℃", "Voltage-Supply(Max)", "Power(Watts)", "Operating Temperature"],
    "PVC board": [],
    "Panel Switch/Panel Socket": ["voltage", "current", "power", "type"],
    "Panel printing materials": [],
    "Panel printing product": [],
    "Paper Dielectric Capacitors": [],
    "Parity Generators and Checkers": ["Voltage - Supply", "Number of Digits", "Logic Type", "Series"],
    "Partition board": [],
    "Passive Filter": [],
    "Patch round nut": ["material", "specifications"],
    "Phillips pan head washer self-drilling screw": [],
    "Photodiodes": [],
    "Photoelectric sensor": [],
    "Photointerrupters - Slot Type - Logic Output": [],
    "Photointerrupters - Slot Type - Transistor Output": ["Load Voltage", "Output Current", "Slot Width", "Peak Wavelength"],
    "Photoresistors": ["Voltage - Max", "Cell Resistance @ Illuminance", "Dark Resistance", "Wavelength - Peak"],
    "Phototransistors": ["Collector - Emitter Voltage VCEO", "Current - Collector(Ic)", "Viewing Angle", "Peak Wavelength"],
    "Photovoltaic (Solar Panel) Connectors": [],
    "Pin & key": ["Diameter", "length", "Standard"],
    "Pin / Jack": [],
    "Pin Headers": ["Pitch", "Number of Pins", "Number of Rows", "Current Rating"],
    "Pin plug": [],
    "Plastic cable drag chain": ["Specifications"],
    "Plug-in cross link assembly": [],
    "Pluggable System Terminal Block": ["Pitch", "Voltage Rating (Max)", "Current Rating", "Number of Positions or Pins"],
    "Pneumatic Tapping Machine": [],
    "Pogo Pin Spring Probe Connector": ["Type", "Number of Pins", "Overall Length/Height"],
    "Polymer Aluminum Capacitors": ["Capacitance", "Voltage Rating", "Equivalent Series Resistance(ESR)", "Ripple Current"],
    "Polypropylene Film Capacitors (CBB)": ["Capacitance", "Voltage Rating", "Tolerance"],
    "Position Sensors": ["Type", "Interface", "Rotation Angle", "Voltage - Supply"],
    "Potentiometer": [],
    "Potentiometers, Variable Resistors": ["Resistance", "Number of Turns", "Power(Watts)", "Tolerance"],
    "Power Distribution Switches": ["Voltage - Supply", "Maximum Continuous Current", "RDS(on)", "Number of Channels"],
    "Power Inductors": ["Inductance", "Current - Saturation(Isat)", "DC Resistance(DCR)", "Current Rating"],
    "Power Management - Specialized": ["Output Voltage", "Output Current", "Topology", "Frequency - Switching"],
    "Power Module/Power Supply": [],
    "Power Over Ethernet (PoE) Controllers": ["Voltage - Supply (IC)", "Type", "Support PoE standard", "Voltage - Breakdown"],
    "Power Relays": ["Contact Rating", "Coil Voltage", "Contact Form", "Switching Voltage(Max)"],
    "Power Sequencers": [],
    "Power Transformers": ["Turns Ratio", "Secondary Side Voltage", "Output Current", "Power(Watts)"],
    "Power connector / plug connector": ["Rated current", "Rated voltage", "contact resistance", "Wire gauge"],
    "Power cord": [],
    "Power line/brake line/extension line": ["Rated voltage", "current", "Rated power", "length"],
    "Power meter": ["Voltage Range", "Current Range", "Power Type", "Accuracy"],
    "Pre-ordered Chips": [],
    "Pre-ordered Connectors": [],
    "Pre-ordered MCUs": [],
    "Pre-ordered RLCs": [],
    "Pre-ordered transistors": [],
    "Precision Op Amps": ["Vos - Input Offset Voltage", "Gain Bandwidth Product", "Number of Channels", "Slew Rate"],
    "Press rivet nut": [],
    "Pressure Sensors": ["Pressure range", "Interface", "Absolute Accuracy", "Voltage - Supply"],
    "Probe": [],
    "Programmable / Variable Gain Amplifiers (PGA/VGA)": ["Gain", "-3dB Bandwidth", "Slew Rate"],
    "Programmable Logic Device (CPLDs/FPGAs)": ["Voltage - Supply (VCCIO)", "Number of Logic Elements/Blocks", "Logic Array Blocks", "Type"],
    "Programmable Oscillators": ["Frequency", "Output Type", "Voltage - Supply", "Frequency Stability"],
    "Proximity Sensor/Proximity Switch": [],
    "Proximity Sensors": ["Sensing Range", "Type", "Voltage - Supply", "Current - Supply"],
    "Pulse Transformers": ["Turns Ratio", "Isolation Voltage(Vrms)", "Inductance", "DC Resistance(DCR)"],
    "Pulse Transformers (LAN)": ["Turns Ratio", "Isolation Voltage(Vrms)", "Number of Channels", "rate"],
    "Push Button Switch": [],
    "Pushbutton Switches": ["Voltage Rating", "Contact Current", "Self Lock / No Lock", "IP Rating"],
    "Quick Terminal": [],
    "RCA Connector": ["Voltage Rating", "Current Rating", "Connector Type", "Number of Ports"],
    "RF Amplifiers": ["Frequency Range", "Gain", "P1dB", "Voltage - Supply"],
    "RF Attenuators": ["Frequency Range", "Attenuation Value", "Impedance", "Power(Watts)"],
    "RF Cables": ["Line Length", "Input/Output", "IPEX Algebra"],
    "RF Detectors": ["Frequency Range", "Input Range", "Accuracy", "Voltage - Supply"],
    "RF Directional Coupler": ["Frequency Range", "Coupling Factor", "Insertion Loss", "Return Loss"],
    "RF Filters": ["Absolute Bandwidth", "Insertion Loss", "Filter Type", "Impedance"],
    "RF Front End Circuits": ["Frequency Range", "Output power", "P1dB(Receive)", "P1dB(Transmit)"],
    "RF Misc ICs and Modules": ["Frequency Range", "Applications", "Function"],
    "RF Mixers": ["Frequency Range", "Gain/Loss", "Noise Figure", "Voltage - Supply"],
    "RF Modulators and Demodulators": ["Frequency Range", "Modulation Type", "Output Power", "Gain"],
    "RF Modules": ["Frequency", "Voltage - Supply", "Modulation System", "Sensitivity"],
    "RF Power Amplifiers": [],
    "RF Power Splitters / Combiners": ["Frequency Range", "Insertion Loss", "Isolation", "Phase Unbalance"],
    "RF Switches": ["Frequency range", "Insertion loss", "isolation", "Voltage - Supply"],
    "RF Transceiver ICs": ["Frequency Range", "Data Rate", "Output Power", "Sensitivity"],
    "RFID ICs": ["Frequency", "transmission rate", "Interface", "agreement"],
    "RFID Modules": ["Type"],
    "RGB LEDs": ["Lens Color", "Viewing Angle", "Diode Configuration"],
    "RGB LEDs(Built-in IC)": ["Wavelength", "Voltage - Supply", "Data Transmission Rate", "Luminous Intensity"],
    "RJ sheath": [],
    "RMS to DC Converters": ["Voltage - Supply", "Current - Supply"],
    "RS-485 / RS-422 ICs": ["Voltage - Supply", "Type", "Number of Drivers", "Number of Receivers", "Data Rate"],
    "RS232 Bus Modules": ["Data Rate", "Voltage - Supply", "ESD Protect", "isolation"],
    "RS232 ICs": ["Voltage - Supply", "Data Rate", "Number of Drivers", "Number of Receivers"],
    "RS485 Bus Modules": ["Data Rate", "Voltage - Supply", "Number of Nodes", "ESD Protect"],
    "Radiator fan accessories": [],
    "Random Access Memory (RAM)": [],
    "Raspberry Pi": [],
    "Real Time Clocks": ["Voltage - Supply", "Interface", "Current - Supply", "Alarm Output"],
    "Receivers & Transceivers": [],
    "Rectangular Cable Assemblies": ["Connector spacing", "Number of positions", "Number of rows", "length"],
    "Reed Relays": ["Coil Voltage", "Switching Voltage(Max)", "Switching Current(Max)", "Contact Form"],
    "Reed Switches": [],
    "Reflective Optical Interrupters": ["Sensing Distance", "Output Type", "Voltage - Forward(Vf)", "Current - Collector(Ic)"],
    "Refrigerant Gauge Set": [],
    "Relay / Coil Drivers": ["RDS(on)", "Operating Temperature"],
    "Relay Sockets and Accessories": [],
    "Relay accessories": [],
    "Relay base": [],
    "Relay module": ["Contact Rating", "Coil Voltage", "Contact Form", "Switching Voltage"],
    "Resettable Fuses": ["Trip Current", "Hold Current", "Current - Max", "Voltage - Max"],
    "Resistance-capacitance inductance measurement/RLC bridge": [],
    "Resistor Networks, Arrays": ["Resistance", "Number of Resistors", "Tolerance", "Power(Watts)"],
    "Right Angle Attachment": [],
    "Ring Terminal": ["Wire Gauge - AWG", "Wire Gauge - mm2", "Connector Type"],
    "Rocker Switches": ["Voltage Rating (DC)", "Current Rating", "Circuit", "Actuator Type"],
    "Rotary Coding Switch": [],
    "Rotary Encoders": ["Rated Voltage (Max)", "Current Rating (Max)", "Encoder Type", "Number of Positions (Absolute)"],
    "Rotary Switches": ["Positions", "Voltage Rating (DC)", "Current Rating", "Number of Poles Per Deck"],
    "Rotary Table": [],
    "Rotary Wheel Switches": ["Switch Gear", "Whether to Press Down"],
    "Round head bolt": [],
    "Rubber plug / rubber cap / protective cover": [],
    "SAMSUNG": ["Core Processor", "Speed", "Program Memory Size", "Number of I/O"],
    "SAW Filters": ["Frequency - Center", "Insertion Loss", "Bandwidth", "Impedance"],
    "SAW Oscillators": [],
    "SAW Resonators": ["Frequency", "Resonant Impedance", "Static Capacitance"],
    "SC Terminal": ["Contact Plating", "Contact Material", "Wire Gauge - SQMM", "Diameter of Bolt Mouth"],
    "SD Card / Memory Card Connector": ["Card Type", "Connector Type", "Card Connection Mode", "Height Above Board"],
    "SDRAM": ["Memory Size", "Clock Frequency", "Voltage - Supply", "Operating Temperature"],
    "SILICON LABS": ["Core Processor", "Speed", "Program Memory Size", "Number of I/O"],
    "SIM Card Connectors": ["Card Type", "Connector Type", "Card Connection Mode", "Card Detection"],
    "SMD Quick Terminal": ["Current Rating", "Pin Spacing(Adjacent)", "Height Above Board", "Terminal Type"],
    "SMD hex nut columns": ["specifications"],
    "SMT": [],
    "SOC": ["Core Processor", "Speed", "Program Memory Size", "Number of I/O"],
    "SPI Isolators": ["Isolation Voltage(Vrms)", "CMTI(kV/us)", "Operating Temperature"],
    "SPI Isolators with power": [],
    "SRAM": ["Memory Size", "Access Time", "Voltage - Supply", "Supply Current (Icc)"],
    "SSD": [],
    "SSRAM": [],
    "ST Microelectronics": ["CPU Core", "CPU Maximum Speed", "Program Storage Size", "RAM Size", "Number of I/O"],
    "STC": ["Core Processor", "Speed", "Program Memory Size", "Number of I/O"],
    "Safety Capacitors": ["Capacitance", "Voltage(AC)", "Tolerance", "Ratings"],
    "Safety Operator": [],
    "Safety Relay": [],
    "Sample / Hold Amplifiers": ["Vos - Input Offset Voltage", "Ib - Input Bias Current"],
    "Schottky Diodes": ["Voltage - DC Reverse(Vr)", "Voltage - Forward(Vf@If)", "Current - Rectified", "Diode Configuration"],
    "Screw & bolt": [],
    "Screw Terminal Blocks": ["Voltage Rating (Max)", "Current Rating", "Number of Positions or Pins", "Wire Gauge - AWG"],
    "Screw tail pin shaft": [],
    "ScrewNut": [],
    "Security Verification / Encryption ICs": ["Voltage - Supply", "Interface", "Standby Current"],
    "Selector Switch": [],
    "Self-aligning roller bearings": [],
    "Semiconductor Discharge Tubes (TSS)": ["Peak off - state voltage(Vdrm)", "On - State Voltage(VT)", "Peak Pulse Current-Ipp (10/1000us)", "Hold Current(Ih)"],
    "Sensor Modules": ["Sensor Type", "Voltage - Supply", "Current - Supply", "Operating Temperature"],
    "Serializers, Deserializers": [],
    "Sewage pump": [],
    "Shielding clip": ["size", "length"],
    "Shift Registers": ["Number of Bits per Element", "Voltage - Supply", "Clock Frequency", "Function"],
    "Shunts, Jumpers": ["Current Rating", "Pitch", "Number of Positions"],
    "SiC Diodes": ["Voltage - DC Reverse(Vr)", "Current - Rectified", "Voltage - Forward(Vf@If)", "Reverse Leakage Current (Ir)"],
    "SiC JFETs": [],
    "Signal Buffers, Repeaters, Splitters": ["Number of Channels", "Voltage - Supply", "Data Rate", "Output Type"],
    "Signal Relays": ["Contact Rating", "Coil Voltage", "Contact Form", "Switching Current(Max)"],
    "Signal Switches, Multiplexers, Decoders": ["Voltage - Supply", "Function", "Type", "Number of lines"],
    "Silicon Capacitors": ["Capacitance", "Voltage - Breakdown", "Tolerance"],
    "Silicon Carbide Field Effect Transistor (MOSFET)": ["Drain to Source Voltage", "Current - Continuous Drain(Id)", "RDS(on)", "Gate Threshold Voltage (Vgs(th))"],
    "Silicone pad": [],
    "Single wire cable (ground wire)": [],
    "Single-ended hex stud": [],
    "Sleeve connector cable": [],
    "Slide Switches": ["Voltage Rating", "Current Rating", "Circuit", "Mounting Type"],
    "Slide table cylinder": [],
    "Socket flat countersunk head screw": [],
    "Socket flat-head machine screw": [],
    "Socket/power strip/extension cord": [],
    "Soft pack battery": [],
    "Solder Terminal": ["voltage", "current", "spacing", "Wire gauge"],
    "Solid State Relays (MOS Output)": ["Load Voltage", "Load Current", "RDS(on)", "Isolation Voltage(Vrms)"],
    "Solid State Relays (Triac Output)": ["Load Voltage", "Load Current", "Current - Surge(Itsm)", "Contact Form"],
    "Solid state relay": [],
    "Solid state relays": [],
    "Sourcing Parts": [],
    "Spade Terminal": ["Wire Gauge - AWG", "Wire Gauge - mm2", "Connector Type"],
    "Speakers": ["Impedance", "Rated Power", "Resonant Frequency", "SPL"],
    "Special Purpose Amplifiers": ["Amplifier Type", "Operating Temperature"],
    "Specialized Sensors": ["Sensor Type", "Interface"],
    "Specialty Logic": [],
    "Specialty Switches": ["Voltage Rating", "Current Rating", "Type"],
    "Spread Spectrum Oscillators (SSOs)": ["Frequency", "Voltage - Supply", "Current - Supply"],
    "Spring": [],
    "Spring Clamp System Terminal Block": ["Pitch", "Current Rating", "Voltage Rating (Max)", "Number of Pins"],
    "Square Copper Terminal": ["Rated Current", "Screw Hole Size", "Body Material", "Ontology Coating"],
    "Square battery": ["nominal voltage", "capacity", "Type"],
    "Star pan head machine screws": ["pitch", "specifications"],
    "Star slot countersunk self-tapping screws": ["standard", "Specifications"],
    "Star slot pan head self-tapping screws": ["standard", "Specifications"],
    "Stepper Motor Driver": ["Output Current", "Motor Drive Voltage(Vm)", "Step Resolution", "Control Voltage"],
    "Studs & Screws": ["diameter", "length", "pitch", "material"],
    "Super Barrier Rectifiers (SBR)": ["Voltage - DC Reverse(Vr)", "Current - Rectified", "Voltage - Forward(Vf@If)", "Diode Configuration"],
    "Supervisor and Reset ICs": ["Threshold Voltage", "Number of Voltages Monitored", "Output Type", "Reset Active Level"],
    "Surge Protection Devices (SPDs)": ["Threshold Voltage", "Voltage Rating", "Number of Lines", "FET Type"],
    "Surge protectors/Lightning protectors": [],
    "Switch Accessories / Caps": ["Shape", "Color"],
    "Switched Capacitor Filters": ["Filter Type", "Filter Order", "Number of Filters"],
    "Switching Diodes": ["Reverse Recovery Time (trr)", "Voltage - DC Reverse(Vr)", "Current - Rectified", "Diode Configuration"],
    "Switching Power Supply Accessories": [],
    "Switching power supply": [],
    "Synchronous Rectifier Controllers": [],
    "T-bolt": [],
    "TF card": [],
    "TI MCU": ["Core Processor", "Speed", "Program Memory Size", "Number of I/O"],
    "Tactile Switch/Push Button Switch": [],
    "Tactile Switches": ["Mounting Type", "Contact Current", "Voltage Rating", "Life"],
    "Tantalum Capacitors": ["Capacitance", "Voltage Rating", "Equivalent Series Resistance(ESR)", "Tolerance"],
    "Tap Collet Chuck": [],
    "TapeMagneticBeads": [],
    "Telecom Interface ICs": ["Voltage - Supply", "Current - Supply", "Operating Temperature"],
    "Temperature Compensated Crystal Oscillators (TCXO)": ["Frequency", "Voltage - Supply", "Frequency Stability", "Operating Temperature"],
    "Temperature Sensing Resonators": [],
    "Temperature Sensors": ["Temperature Range", "Tolerance"],
    "Temperature and Humidity Sensor": ["Interface", "Temperature Range", "Humidity", "Resolution"],
    "Terminal strips": [],
    "Test Points / Test Rings": ["Connector Type", "Board Space"],
    "Test leads": [],
    "Thermal Fuses (TCO)": ["Current Rating", "Voltage Rating", "Maximum Temperature Limit", "Rated Functioning Temperature"],
    "Thermal conductive sheet/thermal conductive cap": ["Type", "ThermalConductivity", "TemperatureResistanceRange"],
    "Thermostat Switches": ["Operating Temperature", "Accuracy of Operating Temperature", "Type"],
    "Threaded Inserts": [],
    "Through Hole Ceramic Capacitors": ["Capacitance", "Voltage Rating", "Tolerance", "Temperature Coefficient"],
    "Through Hole Resistors": ["Resistance", "Tolerance", "Power(Watts)"],
    "Through hole embedded round nuts": [],
    "Thyristors (SCR)/Modules": ["Peak off - state voltage(Vdrm)", "Current - On State(It(RMS))", "Gate Trigger Voltage (Vgt)", "Current - Gate Trigger(Igt)"],
    "Time Delays": ["Voltage - Supply", "Available Total Delays", "Operating Temperature"],
    "Timers / Counters": ["Voltage - Supply", "Frequency", "Current - Supply"],
    "Toggle Switches": ["Voltage Rating (DC)", "Circuit", "Actuator Type", "Mounting Type"],
    "Tool Locking Collar": [],
    "Torsion spring": [],
    "Torsion tester": [],
    "Torx Self-Tapping Screw": [],
    "Touch Screen Controllers": ["Interface", "Resolution (Bits)", "Touch Screen Type", "Voltage - Supply"],
    "Touch Sensors": ["Interface", "Number of Channels", "Voltage - Supply", "Standby Current"],
    "Touch screen": [],
    "Transformer Drivers": ["Input Voltage", "RDS(on)", "Drain to Source Voltage", "Current - Continuous Drain(Id)"],
    "Transistor, Photovoltaic Output Optoisolators": ["Current Transfer Ratio (CTR) Minimum", "Isolation Voltage(Vrms)", "Load Voltage", "Forward Current(If)"],
    "Translators, Level Shifters": ["Voltage - Supply(VCCA)", "Voltage - Supply(VCCB)", "Channel Type", "Number of Elements"],
    "Transmitter": [],
    "Triac, SCR Output Optoisolators": ["Load Voltage", "Load Current", "Isolation Voltage(Vrms)", "Zero Crossing Circuit"],
    "Trigger Diodes": ["Breakover Voltage VBO (Typ)", "Breakover Voltage (Range)", "Breakover Voltage Symmetry", "Breakover Current"],
    "Trimmers, Variable Capacitors": ["Operating Temperature"],
    "Tunable Filters": ["Frequency", "Filter Type", "Filter Order", "Voltage - Supply"],
    "Type T magnetic ring": [],
    "UART": ["Data Rate (Max)", "Number of Channels", "Voltage - Supply", "Interface"],
    "UFS": ["Memory Size", "Voltage - Supply", "Operating Temperature"],
    "USB Connectors": ["Connector Type", "Protocol Standard", "Gender", "Number of Contacts"],
    "USB Conversion Modules": ["Input Port", "Output Port", "Isolation"],
    "USB Converters": ["Voltage - Supply", "USB Protocol", "Data Rate", "Number of Channels"],
    "USB HUB Controllers": ["type", "Number of Channels", "Data Rate", "USB Protocol"],
    "USB PD": ["Type", "Output Power", "Output Voltage", "Protocol"],
    "USB cable/data cable": ["Data Rate", "Voltage - Supply", "ESD Protect", "Quiescent Current"],
    "Ultra high voltage capacitor": [],
    "Ultrasonic Receivers, Transmitters": [],
    "Ultrasonic level gauge": [],
    "Ultraviolet LEDs (UVLED)": ["Peak Wavelength", "Forward Current", "Radiant Flux", "Voltage - Forward(Vf)"],
    "Uncategorized": [],
    "Unclassified goods": [],
    "V-Audio Modules": [],
    "V-Block": [],
    "V/F and F/V Converters": ["Conversion Type VF/FV", "Frequency", "Linearity", "Vos - Input Offset Voltage"],
    "VFD Drivers": ["Voltage - Supply", "Current - Supply", "Interface"],
    "VOC Sensors": [],
    "Vacuum Fluorescent Display Screen": [],
    "Varistors": ["Varistor Voltage", "Maximum DC Volts", "Clamping Voltage", "Energy"],
    "Vibration Motors": ["Voltage Rating", "Current Rating", "Rated Speed"],
    "Vibration Sensors": ["Current Rating", "Voltage Rating", "Temperature Resistance", "Life"],
    "Video Amplifiers": ["-3dB Bandwidth", "Ib - Input Bias Current", "Number of Channels"],
    "Video Interface ICs": ["Type", "Voltage - Supply", "Operating Temperature"],
    "Voltage Controlled Oscillators (VCOs)": ["Voltage - Supply", "Duty Cycle", "Operating Temperature"],
    "Voltage Controlled Temperature Compensated Oscillators (VCTXO)": [],
    "Voltage Reference": ["Output Voltage", "Temperature Coefficient", "Tolerance", "Output Current"],
    "Voltage Regulators - Linear, Low Drop Out (LDO) Regulators": ["Output Voltage", "Output Current", "Voltage Dropout", "Power Supply Rejection Ratio (PSRR)"],
    "Voltage-Controlled Crystal Oscillators (VCXOs)": ["Frequency", "Voltage - Supply", "Output Type", "Frequency Stability"],
    "Washer & retaining ring": [],
    "Water Quality Analyzer": [],
    "Water heater": [],
    "Waterproof LED driver power supply": ["Output Current", "Output Voltage", "Voltage - Input", "Number of Channels"],
    "Weld Screw": [],
    "Welded Elbow": [],
    "Welding sleeves": [],
    "WiFi Modules": ["Frequency", "Interface Type", "Voltage - Supply", "Output Power"],
    "Wire Pin Terminal": ["Contact Plating", "Contact Material", "Wire Gauge - AWG", "Connector Type"],
    "Wire To Board Connector": ["Pitch", "Current Rating", "Voltage Rating", "Pins Structure"],
    "Wire organizer": [],
    "Wireless Charge-Discharge ICs": ["Output Voltage", "Output Current", "Protocol", "Type"],
    "Wireless Charging Coils": ["Inductance", "DC Resistance(DCR)", "Tolerance", "Number of Coils"],
    "Wiring Quick-Connect Terminals": ["Voltage Rating", "Current Rating", "Wire Gauge - AWG", "Wire Gauge - mm2"],
    "XLR (Cannon) Connectors": ["Number of Pins", "Voltage Rating", "Current Rating", "Gender"],
    "Z-Axis Height Setter": [],
    "Z-Axis Setup Device": [],
    "Zener Diodes": ["Zener Voltage(Nom)", "Zener Voltage(Range)", "Pd - Power Dissipation", "Impedance(Zzk)"],
    "ZigBee Modules": ["Interface Type", "Voltage - Supply", "Output Power", "Sensitivity"],
    "circular connector": [],
    "demagnetizer": [],
    "eMMC": ["Memory Size", "Interface", "Reading Speed in Sequence", "Writing Speed in Sequence"],
    "electronic cable": ["Number of Pins"],
    "iButton Memory": ["Memory Size", "Interface", "Voltage - Supply", "Write Cycle Endurance"],
    "indexing head": [],
    "knife sharpener": [],
    "nvSRAM": [],
    "old batch": [],
    "padlock": [],
    "permanent-magnetic chuck": [],
    "plug": [],
    "relay": ["load current", "load type", "rated voltage", "contact types"],
    "sine table": [],
    "sinowealth": ["Core Processor", "Speed", "Program Memory Size", "Number of I/O"],
    "terminal accessories": [],
    "vacuum chuck": [],
    "welding accessories": [],
}
