"""Manufacturer aliases for JLCPCB component search.

Maps common abbreviations and alternate names to the exact manufacturer
names used by the JLCPCB API. Keys are lowercase for case-insensitive lookup.
"""

# Auto-curated from top manufacturers in JLCPCB's catalog
# Keys are lowercase; lookup uses .lower() for case-insensitive matching

MANUFACTURER_ALIASES: dict[str, str] = {
    # Major semiconductor companies
    "ti": "Texas Instruments",
    "texas": "Texas Instruments",
    "texas instruments": "Texas Instruments",
    "stm": "STMicroelectronics",
    "st": "STMicroelectronics",
    "stmicro": "STMicroelectronics",
    "stmicroelectronics": "STMicroelectronics",
    "nxp": "NXP Semicon",
    "nxp semicon": "NXP Semicon",
    "nxp semiconductor": "NXP Semicon",
    "microchip": "Microchip Tech",
    "microchip tech": "Microchip Tech",
    "microchip technology": "Microchip Tech",
    "adi": "Analog Devices",
    "analog": "Analog Devices",
    "analog devices": "Analog Devices",
    "maxim": "Analog Devices Inc./Maxim Integrated",
    "maxim integrated": "Analog Devices Inc./Maxim Integrated",
    "analog devices inc./maxim integrated": "Analog Devices Inc./Maxim Integrated",
    "on": "onsemi",
    "on semi": "onsemi",
    "on semiconductor": "onsemi",
    "onsemi": "onsemi",
    "infineon": "Infineon Technologies",
    "infineon technologies": "Infineon Technologies",
    "cypress": "Infineon/Cypress Semicon",
    "infineon/cypress semicon": "Infineon/Cypress Semicon",
    "renesas": "Renesas Electronics",
    "renesas electronics": "Renesas Electronics",
    "rohm": "ROHM Semicon",
    "rohm semicon": "ROHM Semicon",
    "rohm semiconductor": "ROHM Semicon",
    "vishay": "Vishay Intertech",
    "vishay intertech": "Vishay Intertech",
    "vishay intertechnology": "Vishay Intertech",
    "diodes": "Diodes Incorporated",
    "diodes inc": "Diodes Incorporated",
    "diodes incorporated": "Diodes Incorporated",
    "nexperia": "Nexperia",
    "broadcom": "Broadcom Limited",
    "broadcom limited": "Broadcom Limited",
    "torex": "Torex Semicon",
    "torex semicon": "Torex Semicon",
    # Chinese manufacturers (popular on JLCPCB)
    "fh": "FH (Guangdong Fenghua Advanced Tech)",
    "fenghua": "FH (Guangdong Fenghua Advanced Tech)",
    "fh (guangdong fenghua advanced tech)": "FH (Guangdong Fenghua Advanced Tech)",
    "sxn": "SXN(Shun Xiang Nuo Elec)",
    "sxn(shun xiang nuo elec)": "SXN(Shun Xiang Nuo Elec)",
    "changjing": "Jiangsu Changjing Electronics Technology Co., Ltd.",
    "jiangsu changjing electronics technology co., ltd.": "Jiangsu Changjing Electronics Technology Co., Ltd.",
    "uniroyal": "UNI-ROYAL(Uniroyal Elec)",
    "uni-royal": "UNI-ROYAL(Uniroyal Elec)",
    "uni-royal(uniroyal elec)": "UNI-ROYAL(Uniroyal Elec)",
    "mdd": "MDD(Microdiode Semiconductor)",
    "microdiode": "MDD(Microdiode Semiconductor)",
    "mdd(microdiode semiconductor)": "MDD(Microdiode Semiconductor)",
    "tech public": "TECH PUBLIC",
    "boomele": "BOOMELE(Boom Precision Elec)",
    "boomele(boom precision elec)": "BOOMELE(Boom Precision Elec)",
    "ralec": "RALEC",
    "stc": "STC Micro",
    "stc micro": "STC Micro",
    "kento": "Hubei KENTO Elec",
    "hubei kento elec": "Hubei KENTO Elec",
    "leiditech": "Leiditech",
    "hxy": "HXY MOSFET",
    "hxy mosfet": "HXY MOSFET",
    "sunlord": "Sunlord",
    "slkor": "Slkor(SLKORMICRO Elec.)",
    "slkor(slkormicro elec.)": "Slkor(SLKORMICRO Elec.)",
    "utc": "UTC(Unisonic Tech)",
    "utc(unisonic tech)": "UTC(Unisonic Tech)",
    "holtek": "Holtek Semicon",
    "holtek semicon": "Holtek Semicon",
    # Optoelectronics
    "everlight": "Everlight Elec",
    "everlight elec": "Everlight Elec",
    "osram": "OSRAM Opto Semicon",
    "osram opto semicon": "OSRAM Opto Semicon",
    "lite-on": "Lite-On",
    "liteon": "Lite-On",
    "sharp": "Sharp Microelectronics",
    "sharp microelectronics": "Sharp Microelectronics",
    # Connectors
    "kangnex": "Ningbo Kangnex Elec",
    "ningbo kangnex elec": "Ningbo Kangnex Elec",
    "jst": "JST",
    # Passives
    "samsung": "Samsung Electro-Mechanics",
    "samsung electro-mechanics": "Samsung Electro-Mechanics",
    "yageo": "YAGEO",
    "murata": "Murata Electronics",
    "murata electronics": "Murata Electronics",
    "tdk": "TDK Corporation",
    "tdk corporation": "TDK Corporation",
    "panasonic": "Panasonic",
    "wurth": "Wurth Elektronik",
    "würth": "Wurth Elektronik",
    "wurth elektronik": "Wurth Elektronik",
    "bourns": "Bourns",
    "littelfuse": "Littelfuse",
    # MCU/SoC
    "espressif": "Espressif Systems",
    "espressif systems": "Espressif Systems",
    "nordic": "Nordic Semicon",
    "nordic semicon": "Nordic Semicon",
    "nordic semiconductor": "Nordic Semicon",
    "silabs": "Silicon Labs",
    "silicon labs": "Silicon Labs",
    "raspberry pi": "Raspberry Pi",
    "rpi": "Raspberry Pi",
    # Memory
    "winbond": "Winbond Elec",
    "winbond elec": "Winbond Elec",
    "micron": "Micron Tech",
    "micron tech": "Micron Tech",
    "micron technology": "Micron Tech",
    "issi": "ISSI(Integrated Silicon Solution)",
    "issi(integrated silicon solution)": "ISSI(Integrated Silicon Solution)",
    "macronix": "MXIC(Macronix)",
    "mxic": "MXIC(Macronix)",
    "mxic(macronix)": "MXIC(Macronix)",
    "ramxeed": "RAMXEED/FUJITSU",
    "fujitsu": "RAMXEED/FUJITSU",
    "ramxeed/fujitsu": "RAMXEED/FUJITSU",
    # Motor drivers / Power
    "allegro": "Allegro MicroSystems, LLC",
    "allegro microsystems": "Allegro MicroSystems, LLC",
    "allegro microsystems, llc": "Allegro MicroSystems, LLC",
    "richtek": "Richtek Tech",
    "richtek tech": "Richtek Tech",
    # Connectors
    "amphenol": "Amphenol ICC",
    "amphenol icc": "Amphenol ICC",
    "te": "TE Connectivity",
    "te connectivity": "TE Connectivity",
    "xkb": "XKB Connection",
    "xkb connection": "XKB Connection",
    "kinghelm": "Shenzhen Kinghelm Elec",
    # Relays
    "omron": "Omron Electronics",
    "omron electronics": "Omron Electronics",
    "hongfa": "HF(Xiamen Hongfa Electroacoustic)",
    "hf": "HF(Xiamen Hongfa Electroacoustic)",
    "hf(xiamen hongfa electroacoustic)": "HF(Xiamen Hongfa Electroacoustic)",
    "songle": "Ningbo Songle Relay",
    "ningbo songle relay": "Ningbo Songle Relay",
    "hke": "Zhejiang HKE",
    "zhejiang hke": "Zhejiang HKE",
    # Sensors
    "sensirion": "Sensirion",
    "invensense": "TDK InvenSense",
    "tdk invensense": "TDK InvenSense",
    # Chinese IC makers
    "belling": "BL(Shanghai Belling)",
    "shanghai belling": "BL(Shanghai Belling)",
    "bl": "BL(Shanghai Belling)",
    "bl(shanghai belling)": "BL(Shanghai Belling)",
    "on-bright": "OB(On-Bright Elec)",
    "onbright": "OB(On-Bright Elec)",
    "ob": "OB(On-Bright Elec)",
    "ob(on-bright elec)": "OB(On-Bright Elec)",
    "hctl": "HCTL",
    "prisemi": "Shanghai Prisemi Elec",
    "shanghai prisemi elec": "Shanghai Prisemi Elec",
    # Japanese
    "toshiba": "TOSHIBA",
    "jrc": "JRC",
    # Other
    "semtech": "ST(Semtech)",
    "st(semtech)": "ST(Semtech)",
    "maxlinear": "MaxLinear",
    "pulse": "Pulse Elec",
    "pulse elec": "Pulse Elec",
}
